services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - MICROPHONE_DEVICE_INDEX=${MICROPHONE_DEVICE_INDEX}
    ports:
      - "5000:5000"
    expose:
      - 5000
    networks:
      - app-network

networks:
  app-network:
    driver:
      bridge
      
