services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - 5000
    networks:
      - app-network

networks:
  app-network:
    driver:
      bridge
      
